#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
    echo "Must source and OpenCFD OpenFOAM version for this to work!"
    exit 1
fi

if [ ! -d "$1" ];  then
    echo "Must pass in the scripts folder as first argument"
    exit 1
fi
scripts_folder="$1"

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

set -e
touch case.foam
uv run --script "$scripts_folder"/update-controlDict.py
uv run --script "$scripts_folder"/generate.py
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication snappyHexMesh -overwrite
rm -rf 0
runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite
restore0Dir
runApplication decomposePar
runParallel $(getApplication)

#------------------------------------------------------------------------------
