#!/bin/sh
source "$1/etc/bashrc"
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

set -e
touch case.foam
runApplication ./update-controlDict.py
runApplication ./geometry/generate.py
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication snappyHexMesh -overwrite
rm -rf 0
runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite
restore0Dir
runApplication decomposePar
runParallel $(getApplication)

#------------------------------------------------------------------------------
